### ISSUE TITLE
Rework Tutorials Section

### ISSUE THREAD

**Issue by ralph-lange** [micro-ROS/micro-ROS.github.io#109]
- [x] Change "Basic tutorials" to "Core tutorials" with pages on
    - Hello World with micro-ROS (simple echo node with topics /ping and /pong), see #143 
    - Programming with rcl and rclc, see #113 and #143
    - rclc Executor, see #143 
    - [x] Benchmarking micro-ROS applications (put "Tracing with ROS 2" here inside? Does this make sense?) @amx-piap 
    - [x] Setting up the rmw for Micro-XRCE-DDS (incl. best-effort vs reliable) https://github.com/micro-ROS/micro-ROS.github.io/pull/111 @pablogs9 

- [ ] Improve demo subsection. Finally should be five pages on
    - [ ] Kobuki Demo (NuttX) @iluetkeb 
    - [x] Crazyflie Demo (FreeRTOS) #131 @jfm92
    - [x] ToF Sensor #134 (Zephyr) @julibert 
    - [ ] Interfacing with the FIWARE Context Broker (ToF Sensor via Context Broker) 
    - [ ] Joint Kobuki - Crazyflie - ToF Sensor - FIWARE Context Broker Demo @julibert 

- [x] Introduce new Advanced Tutorials with NuttX subsection. Organize pages into
    - [x] Rename "Advanced tutorials" to "Advanced Tutorials with NuttX"
    - [x] NuttX in Depth - split existing page up #127  @jfm92
    - [x] Debugging a NuttX target (incl. VS Code) @jfm92
    - [x] 6LoWPAN with NuttX @jfm92
    - [x] Simulator (if possible) (blocked) @jfm92
    - [x] Adding Micro-ROS to a NuttX board configuration (blocked) @jfm92

- [x] Introduce new empty subsection named "Advanced Tutorials with FreeRTOS" https://github.com/micro-ROS/micro-ROS.github.io/pull/114 @pablogs9 

- [x] Introduce new subsection named "Advanced Tutorials with Zephyr" @julibert 
    - [x] Create a tutorial page on Zephyr simulator @julibert 

Other issues:
- [x] Where to put "Tracing with ROS 2" if not integrated into benchmarking page? "Advanced tutorials with Linux" subsection (@ralph-lange)

- [x] Create empty pages where missing (@ralph-lange, @pablogs9 )

**Comment by ralph-lange** [comment]
More details on the Hello World tutorial:
- Assume basic knowledge of ROS 2 and that ROS 2 is installed on desktop/laptop
- Include code for echo node on the MCU with topics /ping and /pong
- Should be one tutorial page only, but possibly with RTOS-specific paragraphs
- Echo function to be tested by user from ROS 2 on the command line

**Comment by amx-piap** [comment]
Regarding the Ros2 Tracing and benchmarking , we can have seperated section:
 -   Tracing:
                  - ROS2 Tracing etc..
                  - Tracing in Benchmarking (more information how to exploit traces for benchmarks).
 -   Benchmarking (Dedicated section about benchmarking)

**Comment by FranFin** [comment]
@ralph-lange Closing this issue as the pages referring to the demos have been created, even though content is missing.
